const mongoose = require('mongoose');
const Product = require('./models/Product');
require('dotenv').config();

const sampleProducts = [
  {
    name: 'Samsung Galaxy S24 Ultra 5G',
    description: 'Latest flagship smartphone with 200MP camera, S Pen, and AI features. 12GB RAM, 256GB storage, titanium frame.',
    price: 134999,
    originalPrice: 149999,
    discount: 10,
    category: 'Mobiles',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500'],
    rating: 4.6,
    numReviews: 245,
    stock: 50,
    features: ['200MP Camera', 'S Pen Included', 'AI Features', 'Titanium Frame'],
    specifications: new Map([['Display', '6.8 inch QHD+'], ['RAM', '12GB'], ['Storage', '256GB'], ['Processor', 'Snapdragon 8 Gen 3']]),
    isFeatured: true,
    tags: ['smartphone', '5g', 'premium']
  },
  {
    name: 'Apple iPhone 15 Pro Max',
    description: 'A17 Pro chip, titanium design, 48MP camera system, Action button. The most powerful iPhone ever.',
    price: 159900,
    originalPrice: 179900,
    discount: 11,
    category: 'Mobiles',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500'],
    rating: 4.8,
    numReviews: 312,
    stock: 35,
    features: ['A17 Pro Chip', 'Titanium Design', '48MP Camera', 'Action Button'],
    specifications: new Map([['Display', '6.7 inch Super Retina XDR'], ['RAM', '8GB'], ['Storage', '256GB'], ['Processor', 'A17 Pro']]),
    isFeatured: true,
    tags: ['iphone', 'premium', '5g']
  },
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise cancellation with 8 microphones. 30-hour battery life, multipoint connection.',
    price: 29990,
    originalPrice: 34990,
    discount: 14,
    category: 'Electronics',
    brand: 'Sony',
    images: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500'],
    rating: 4.7,
    numReviews: 189,
    stock: 75,
    features: ['Active Noise Cancellation', '30hr Battery', 'Multipoint Connection', 'LDAC Support'],
    specifications: new Map([['Driver Size', '30mm'], ['Battery', '30 hours'], ['Weight', '250g'], ['Bluetooth', '5.2']]),
    isFeatured: true,
    tags: ['headphones', 'noise-cancelling', 'wireless']
  },
  {
    name: 'Dell XPS 15 Laptop',
    description: 'Intel Core i7, 16GB RAM, 512GB SSD, NVIDIA RTX 4050. 15.6 inch OLED display.',
    price: 154990,
    originalPrice: 174990,
    discount: 11,
    category: 'Electronics',
    brand: 'Dell',
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500'],
    rating: 4.5,
    numReviews: 98,
    stock: 25,
    features: ['OLED Display', 'RTX 4050 GPU', 'Thunderbolt 4', 'Fingerprint Reader'],
    specifications: new Map([['Processor', 'Intel Core i7'], ['RAM', '16GB'], ['Storage', '512GB SSD'], ['Display', '15.6 inch OLED']]),
    isFeatured: true,
    tags: ['laptop', 'gaming', 'professional']
  },
  {
    name: 'Nike Air Jordan 1 Retro High',
    description: 'Iconic basketball sneaker with premium leather upper. Air-Sole unit for lightweight cushioning.',
    price: 16995,
    originalPrice: 18995,
    discount: 11,
    category: 'Fashion',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
    rating: 4.4,
    numReviews: 156,
    stock: 100,
    features: ['Premium Leather', 'Air-Sole Cushioning', 'Classic Design', 'Rubber Outsole'],
    specifications: new Map([['Upper', 'Leather'], ['Sole', 'Rubber'], ['Closure', 'Lace-up'], ['Style', 'High Top']]),
    isFeatured: true,
    tags: ['sneakers', 'basketball', 'retro']
  },
  {
    name: 'Ray-Ban Aviator Classic Sunglasses',
    description: 'Timeless aviator style with gradient lenses. Metal frame with crystal lenses.',
    price: 12999,
    originalPrice: 14999,
    discount: 13,
    category: 'Fashion',
    brand: 'Ray-Ban',
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500'],
    rating: 4.6,
    numReviews: 234,
    stock: 150,
    features: ['Gradient Lenses', 'Metal Frame', 'UV Protection', 'Classic Design'],
    specifications: new Map([['Frame', 'Metal'], ['Lens', 'Crystal Gradient'], ['UV', '400'], ['Size', '58mm']]),
    isFeatured: true,
    tags: ['sunglasses', 'accessories', 'classic']
  },
  {
    name: 'Lakme Absolute Skin Serum Foundation',
    description: 'Long-lasting foundation with serum benefits. SPF 45, 24hr wear, natural matte finish.',
    price: 899,
    originalPrice: 1099,
    discount: 18,
    category: 'Beauty',
    brand: 'Lakme',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500'],
    rating: 4.3,
    numReviews: 445,
    stock: 200,
    features: ['SPF 45', '24hr Wear', 'Serum Enriched', 'Matte Finish'],
    specifications: new Map([['Shade', 'Multiple'], ['Coverage', 'Medium to Full'], ['Finish', 'Matte'], ['Weight', '30ml']]),
    isFeatured: true,
    tags: ['makeup', 'foundation', 'skincare']
  },
  {
    name: 'Forest Essentials Luxury Facial Kit',
    description: 'Complete facial kit with natural ingredients. Includes cleanser, toner, serum, and moisturizer.',
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    category: 'Beauty',
    brand: 'Forest Essentials',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500'],
    rating: 4.5,
    numReviews: 178,
    stock: 80,
    features: ['Natural Ingredients', 'Complete Kit', 'Ayurvedic Formula', 'Luxury Packaging'],
    specifications: new Map([['Type', 'Facial Kit'], ['Skin Type', 'All'], ['Products', '4'], ['Weight', '200g']]),
    isFeatured: true,
    tags: ['skincare', 'ayurvedic', 'luxury']
  },
  {
    name: 'Godrej Interio Sofa Set',
    description: '3+1+1 sofa set with premium fabric upholstery. Solid wood frame, high-density foam.',
    price: 45999,
    originalPrice: 54999,
    discount: 16,
    category: 'Home',
    brand: 'Godrej',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500'],
    rating: 4.2,
    numReviews: 67,
    stock: 15,
    features: ['Premium Fabric', 'Solid Wood Frame', 'High-Density Foam', '5 Year Warranty'],
    specifications: new Map([['Seating', '3+1+1'], ['Material', 'Fabric/Wood'], ['Dimensions', 'L: 84 W: 36 H: 34'], ['Color', 'Multiple']]),
    isFeatured: true,
    tags: ['furniture', 'sofa', 'living-room']
  },
  {
    name: 'Philips Air Fryer HD9650/90',
    description: 'Rapid Air technology for healthier frying. 1.8kg capacity, digital display, 7 presets.',
    price: 12995,
    originalPrice: 15995,
    discount: 19,
    category: 'Appliances',
    brand: 'Philips',
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=500'],
    rating: 4.4,
    numReviews: 289,
    stock: 60,
    features: ['Rapid Air Tech', '1.8kg Capacity', 'Digital Display', '7 Presets'],
    specifications: new Map([['Capacity', '1.8kg'], ['Power', '2225W'], ['Presets', '7'], ['Timer', '60min']]),
    isFeatured: true,
    tags: ['air-fryer', 'kitchen', 'healthy']
  },
  {
    name: 'Yonex Astrox 99 Pro Badminton Racket',
    description: 'Professional grade racket with Nanomesh Neo technology. Head heavy balance for power.',
    price: 18999,
    originalPrice: 21999,
    discount: 14,
    category: 'Sports',
    brand: 'Yonex',
    images: ['https://images.unsplash.com/photo-1617886903355-9354bb57771f?w=500'],
    rating: 4.7,
    numReviews: 123,
    stock: 40,
    features: ['Nanomesh Neo', 'Head Heavy', 'Isometric Head', 'Control Support Cap'],
    specifications: new Map([['Weight', '88g'], ['Balance', 'Head Heavy'], ['Flex', 'Stiff'], ['Tension', 'Up to 30lbs']]),
    isFeatured: true,
    tags: ['badminton', 'racket', 'professional']
  },
  {
    name: 'Tata Sampann Unpolished Toor Dal',
    description: 'Premium quality unpolished toor dal. 1kg pack, rich in protein, easy to digest.',
    price: 140,
    originalPrice: 160,
    discount: 13,
    category: 'Grocery',
    brand: 'Tata Sampann',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500'],
    rating: 4.5,
    numReviews: 567,
    stock: 500,
    features: ['Unpolished', 'High Protein', 'Easy to Digest', 'No Preservatives'],
    specifications: new Map([['Weight', '1kg'], ['Type', 'Toor Dal'], ['Packaging', 'Pouch'], ['Origin', 'India']]),
    isFeatured: true,
    tags: ['grocery', 'dal', 'staple']
  },
  {
    name: 'OnePlus 12 5G',
    description: 'Snapdragon 8 Gen 3, 16GB RAM, 512GB storage. Hasselblad camera system, 100W charging.',
    price: 64999,
    originalPrice: 69999,
    discount: 7,
    category: 'Mobiles',
    brand: 'OnePlus',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500'],
    rating: 4.5,
    numReviews: 198,
    stock: 45,
    features: ['Snapdragon 8 Gen 3', 'Hasselblad Camera', '100W Charging', '16GB RAM'],
    specifications: new Map([['Display', '6.82 inch LTPO AMOLED'], ['RAM', '16GB'], ['Storage', '512GB'], ['Battery', '5400mAh']]),
    isFeatured: false,
    tags: ['smartphone', '5g', 'flagship']
  },
  {
    name: 'Canon EOS R6 Mark II Camera',
    description: '24.2MP full-frame mirrorless camera. 4K 60fps video, 40fps continuous shooting.',
    price: 215990,
    originalPrice: 239990,
    discount: 10,
    category: 'Electronics',
    brand: 'Canon',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500'],
    rating: 4.8,
    numReviews: 45,
    stock: 20,
    features: ['24.2MP Full-Frame', '4K 60fps', '40fps Shooting', 'Dual Card Slots'],
    specifications: new Map([['Sensor', '24.2MP Full-Frame'], ['Video', '4K 60fps'], ['ISO', '100-102400'], ['AF Points', '1053']]),
    isFeatured: false,
    tags: ['camera', 'mirrorless', 'professional']
  },
  {
    name: 'Adidas Ultraboost 22 Running Shoes',
    description: 'Energy-returning Boost midsole. Primeknit upper, Continental rubber outsole.',
    price: 15999,
    originalPrice: 17999,
    discount: 11,
    category: 'Sports',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500'],
    rating: 4.6,
    numReviews: 234,
    stock: 85,
    features: ['Boost Midsole', 'Primeknit Upper', 'Continental Rubber', 'Energy Return'],
    specifications: new Map([['Type', 'Running'], ['Drop', '10mm'], ['Weight', '310g'], ['Surface', 'Road']]),
    isFeatured: false,
    tags: ['running', 'shoes', 'performance']
  },
  {
    name: 'FabIndia Cotton Kurta Set',
    description: 'Traditional cotton kurta with pajama. Hand-block printed, breathable fabric.',
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    category: 'Fashion',
    brand: 'FabIndia',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500'],
    rating: 4.3,
    numReviews: 167,
    stock: 120,
    features: ['100% Cotton', 'Hand Block Print', 'Breathable', 'Traditional Design'],
    specifications: new Map([['Material', 'Cotton'], ['Set', 'Kurta + Pajama'], ['Sizes', 'S to XXL'], ['Care', 'Machine Wash']]),
    isFeatured: false,
    tags: ['ethnic', 'kurta', 'traditional']
  },
  {
    name: 'LG 55 inch 4K OLED TV',
    description: '55 inch OLED display with Dolby Vision IQ. AI ThinQ, webOS, 4 HDMI ports.',
    price: 119990,
    originalPrice: 139990,
    discount: 14,
    category: 'Appliances',
    brand: 'LG',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500'],
    rating: 4.7,
    numReviews: 89,
    stock: 30,
    features: ['OLED Display', 'Dolby Vision IQ', 'AI ThinQ', 'G-Sync Compatible'],
    specifications: new Map([['Display', '55 inch OLED'], ['Resolution', '4K'], ['Refresh Rate', '120Hz'], ['HDR', 'Dolby Vision']]),
    isFeatured: false,
    tags: ['tv', 'oled', 'smart-tv']
  },
  {
    name: 'Mamaearth Vitamin C Serum',
    description: 'Face serum with vitamin C and hyaluronic acid. Brightens skin, reduces dark spots.',
    price: 549,
    originalPrice: 699,
    discount: 21,
    category: 'Beauty',
    brand: 'Mamaearth',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500'],
    rating: 4.4,
    numReviews: 523,
    stock: 300,
    features: ['Vitamin C', 'Hyaluronic Acid', 'Natural Ingredients', 'Dermatologist Tested'],
    specifications: new Map([['Volume', '30ml'], ['Skin Type', 'All'], ['Use', 'Daily'], ['Gender', 'Unisex']]),
    isFeatured: false,
    tags: ['serum', 'skincare', 'vitamin-c']
  },
  {
    name: 'Urban Company Home Cleaning Kit',
    description: 'Complete home cleaning kit with microfiber cloths, brushes, and cleaning solutions.',
    price: 999,
    originalPrice: 1299,
    discount: 23,
    category: 'Home',
    brand: 'Urban Company',
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500'],
    rating: 4.2,
    numReviews: 345,
    stock: 180,
    features: ['Microfiber Cloths', 'Cleaning Brushes', 'Eco-Friendly', 'Multi-Surface'],
    specifications: new Map([['Items', '12'], ['Type', 'Cleaning Kit'], ['Material', 'Microfiber'], ['Warranty', '1 Year']]),
    isFeatured: false,
    tags: ['cleaning', 'home', 'kit']
  },
  {
    name: 'Amul Taaza Homogenised Milk',
    description: 'Fresh homogenised milk, 1 liter. Pasteurized, rich in calcium and protein.',
    price: 68,
    originalPrice: 72,
    discount: 6,
    category: 'Grocery',
    brand: 'Amul',
    images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500'],
    rating: 4.6,
    numReviews: 789,
    stock: 1000,
    features: ['Pasteurized', 'Homogenised', 'Rich in Calcium', 'Fresh'],
    specifications: new Map([['Volume', '1 Liter'], ['Fat', '3%'], ['Type', 'Cow Milk'], ['Shelf Life', '2 days']]),
    isFeatured: false,
    tags: ['milk', 'dairy', 'fresh']
  }
];

mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/indian-shopping')
  .then(() => {
    console.log('MongoDB Connected');
    return Product.deleteMany({});
  })
  .then(() => {
    console.log('Old products deleted');
    return Product.insertMany(sampleProducts);
  })
  .then(() => {
    console.log('Sample products inserted');
    process.exit();
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
