const mongoose = require('mongoose');
const Product = require('./models/Product');
require('dotenv').config();

const sampleProducts = [
  // ==================== MOBILES ====================
  {
    name: 'Samsung Galaxy S24 Ultra 5G',
    description: 'Latest flagship smartphone with 200MP camera, S Pen, and AI features. 12GB RAM, 256GB storage, titanium frame.',
    price: 134999,
    originalPrice: 149999,
    discount: 10,
    category: 'Mobiles',
    brand: 'Samsung',
    images: ['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500'],
    rating: 4.6,
    numReviews: 245,
    stock: 50,
    features: ['200MP Camera', 'S Pen Included', 'AI Features', 'Titanium Frame'],
    specifications: new Map([['Display', '6.8 inch QHD+'], ['RAM', '12GB'], ['Storage', '256GB'], ['Processor', 'Snapdragon 8 Gen 3']]),
    isFeatured: true,
    tags: ['smartphone', '5g', 'premium']
  },
  {
    name: 'Apple iPhone 15 Pro Max',
    description: 'A17 Pro chip, titanium design, 48MP camera system, Action button. The most powerful iPhone ever.',
    price: 159900,
    originalPrice: 179900,
    discount: 11,
    category: 'Mobiles',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500'],
    rating: 4.8,
    numReviews: 312,
    stock: 35,
    features: ['A17 Pro Chip', 'Titanium Design', '48MP Camera', 'Action Button'],
    specifications: new Map([['Display', '6.7 inch Super Retina XDR'], ['RAM', '8GB'], ['Storage', '256GB'], ['Processor', 'A17 Pro']]),
    isFeatured: true,
    tags: ['iphone', 'premium', '5g']
  },
  {
    name: 'OnePlus 12 5G',
    description: 'Snapdragon 8 Gen 3, 16GB RAM, 512GB storage. Hasselblad camera system, 100W charging.',
    price: 64999,
    originalPrice: 69999,
    discount: 7,
    category: 'Mobiles',
    brand: 'OnePlus',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500'],
    rating: 4.5,
    numReviews: 198,
    stock: 45,
    features: ['Snapdragon 8 Gen 3', 'Hasselblad Camera', '100W Charging', '16GB RAM'],
    specifications: new Map([['Display', '6.82 inch LTPO AMOLED'], ['RAM', '16GB'], ['Storage', '512GB'], ['Battery', '5400mAh']]),
    isFeatured: false,
    tags: ['smartphone', '5g', 'flagship']
  },
  {
    name: 'Redmi Note 13 Pro+',
    description: '200MP camera, 120W HyperCharge, 6.67 inch AMOLED display. Best mid-range smartphone.',
    price: 29999,
    originalPrice: 34999,
    discount: 14,
    category: 'Mobiles',
    brand: 'Redmi',
    images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500'],
    rating: 4.4,
    numReviews: 432,
    stock: 80,
    features: ['200MP Camera', '120W Charging', 'AMOLED Display', '5000mAh Battery'],
    specifications: new Map([['Display', '6.67 inch AMOLED'], ['RAM', '8GB'], ['Storage', '256GB'], ['Battery', '5000mAh']]),
    isFeatured: true,
    tags: ['smartphone', 'mid-range', 'camera']
  },
  {
    name: 'Realme GT 5 Pro',
    description: 'Snapdragon 8 Gen 3, 240W SuperVOOC charging, 50MP periscope camera.',
    price: 49999,
    originalPrice: 54999,
    discount: 9,
    category: 'Mobiles',
    brand: 'Realme',
    images: ['https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=500'],
    rating: 4.3,
    numReviews: 156,
    stock: 60,
    features: ['240W Charging', 'Snapdragon 8 Gen 3', '50MP Periscope', '5400mAh Battery'],
    specifications: new Map([['Display', '6.78 inch AMOLED'], ['RAM', '12GB'], ['Storage', '256GB'], ['Battery', '5400mAh']]),
    isFeatured: false,
    tags: ['smartphone', 'fast-charging', '5g']
  },

  // ==================== ELECTRONICS ====================
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise cancellation with 8 microphones. 30-hour battery life, multipoint connection.',
    price: 29990,
    originalPrice: 34990,
    discount: 14,
    category: 'Electronics',
    brand: 'Sony',
    images: ['https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500'],
    rating: 4.7,
    numReviews: 189,
    stock: 75,
    features: ['Active Noise Cancellation', '30hr Battery', 'Multipoint Connection', 'LDAC Support'],
    specifications: new Map([['Driver Size', '30mm'], ['Battery', '30 hours'], ['Weight', '250g'], ['Bluetooth', '5.2']]),
    isFeatured: true,
    tags: ['headphones', 'noise-cancelling', 'wireless']
  },
  {
    name: 'Dell XPS 15 Laptop',
    description: 'Intel Core i7, 16GB RAM, 512GB SSD, NVIDIA RTX 4050. 15.6 inch OLED display.',
    price: 154990,
    originalPrice: 174990,
    discount: 11,
    category: 'Electronics',
    brand: 'Dell',
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500'],
    rating: 4.5,
    numReviews: 98,
    stock: 25,
    features: ['OLED Display', 'RTX 4050 GPU', 'Thunderbolt 4', 'Fingerprint Reader'],
    specifications: new Map([['Processor', 'Intel Core i7'], ['RAM', '16GB'], ['Storage', '512GB SSD'], ['Display', '15.6 inch OLED']]),
    isFeatured: true,
    tags: ['laptop', 'gaming', 'professional']
  },
  {
    name: 'Canon EOS R6 Mark II Camera',
    description: '24.2MP full-frame mirrorless camera. 4K 60fps video, 40fps continuous shooting.',
    price: 215990,
    originalPrice: 239990,
    discount: 10,
    category: 'Electronics',
    brand: 'Canon',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500'],
    rating: 4.8,
    numReviews: 45,
    stock: 20,
    features: ['24.2MP Full-Frame', '4K 60fps', '40fps Shooting', 'Dual Card Slots'],
    specifications: new Map([['Sensor', '24.2MP Full-Frame'], ['Video', '4K 60fps'], ['ISO', '100-102400'], ['AF Points', '1053']]),
    isFeatured: false,
    tags: ['camera', 'mirrorless', 'professional']
  },
  {
    name: 'Apple iPad Pro 12.9 inch M2',
    description: 'M2 chip, Liquid Retina XDR display, Apple Pencil support, 5G connectivity.',
    price: 112900,
    originalPrice: 129900,
    discount: 13,
    category: 'Electronics',
    brand: 'Apple',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500'],
    rating: 4.8,
    numReviews: 234,
    stock: 30,
    features: ['M2 Chip', 'Liquid Retina XDR', 'Apple Pencil Support', '5G'],
    specifications: new Map([['Display', '12.9 inch Liquid Retina XDR'], ['Chip', 'M2'], ['Storage', '256GB'], ['Battery', '10hr']]),
    isFeatured: true,
    tags: ['ipad', 'tablet', 'apple']
  },
  {
    name: 'boAt Airdopes 141 TWS Earbuds',
    description: '42 hours total playback, BEAST Mode for gaming, ENx technology for clear calls.',
    price: 1299,
    originalPrice: 2990,
    discount: 57,
    category: 'Electronics',
    brand: 'boAt',
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500'],
    rating: 4.2,
    numReviews: 8934,
    stock: 500,
    features: ['42hr Playback', 'BEAST Mode', 'ENx Technology', 'IPX4 Water Resistant'],
    specifications: new Map([['Battery', '42 hours total'], ['Driver', '8mm'], ['Bluetooth', '5.0'], ['Weight', '4.5g each']]),
    isFeatured: true,
    tags: ['earbuds', 'tws', 'wireless']
  },

  // ==================== FASHION ====================
  {
    name: 'Nike Air Jordan 1 Retro High',
    description: 'Iconic basketball sneaker with premium leather upper. Air-Sole unit for lightweight cushioning.',
    price: 16995,
    originalPrice: 18995,
    discount: 11,
    category: 'Fashion',
    brand: 'Nike',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
    rating: 4.4,
    numReviews: 156,
    stock: 100,
    features: ['Premium Leather', 'Air-Sole Cushioning', 'Classic Design', 'Rubber Outsole'],
    specifications: new Map([['Upper', 'Leather'], ['Sole', 'Rubber'], ['Closure', 'Lace-up'], ['Style', 'High Top']]),
    isFeatured: true,
    tags: ['sneakers', 'basketball', 'retro']
  },
  {
    name: 'Ray-Ban Aviator Classic Sunglasses',
    description: 'Timeless aviator style with gradient lenses. Metal frame with crystal lenses.',
    price: 12999,
    originalPrice: 14999,
    discount: 13,
    category: 'Fashion',
    brand: 'Ray-Ban',
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500'],
    rating: 4.6,
    numReviews: 234,
    stock: 150,
    features: ['Gradient Lenses', 'Metal Frame', 'UV Protection', 'Classic Design'],
    specifications: new Map([['Frame', 'Metal'], ['Lens', 'Crystal Gradient'], ['UV', '400'], ['Size', '58mm']]),
    isFeatured: true,
    tags: ['sunglasses', 'accessories', 'classic']
  },
  {
    name: 'FabIndia Cotton Kurta Set',
    description: 'Traditional cotton kurta with pajama. Hand-block printed, breathable fabric.',
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    category: 'Fashion',
    brand: 'FabIndia',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500'],
    rating: 4.3,
    numReviews: 167,
    stock: 120,
    features: ['100% Cotton', 'Hand Block Print', 'Breathable', 'Traditional Design'],
    specifications: new Map([['Material', 'Cotton'], ['Set', 'Kurta + Pajama'], ['Sizes', 'S to XXL'], ['Care', 'Machine Wash']]),
    isFeatured: false,
    tags: ['ethnic', 'kurta', 'traditional']
  },
  {
    name: 'Taneira Banarasi Silk Saree',
    description: 'Pure Banarasi silk saree with golden zari work. Perfect for weddings and festivities.',
    price: 18999,
    originalPrice: 24999,
    discount: 24,
    category: 'Fashion',
    brand: 'Taneira',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500'],
    rating: 4.7,
    numReviews: 89,
    stock: 40,
    features: ['Pure Silk', 'Zari Work', 'Wedding Special', 'Comes with Blouse Piece'],
    specifications: new Map([['Material', 'Pure Silk'], ['Length', '6.3 meters'], ['Blouse', 'Included'], ['Occasion', 'Wedding/Festival']]),
    isFeatured: true,
    tags: ['saree', 'silk', 'ethnic', 'wedding']
  },
  {
    name: 'Peter England Men Formal Shirt',
    description: 'Premium cotton formal shirt, wrinkle-free fabric, slim fit design for office wear.',
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    category: 'Fashion',
    brand: 'Peter England',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500'],
    rating: 4.3,
    numReviews: 567,
    stock: 200,
    features: ['Wrinkle Free', 'Slim Fit', '100% Cotton', 'Machine Washable'],
    specifications: new Map([['Material', 'Cotton'], ['Fit', 'Slim'], ['Sizes', 'S to XXL'], ['Care', 'Machine Wash']]),
    isFeatured: false,
    tags: ['shirt', 'formal', 'men', 'office']
  },

  // ==================== BEAUTY ====================
  {
    name: 'Lakme Absolute Skin Serum Foundation',
    description: 'Long-lasting foundation with serum benefits. SPF 45, 24hr wear, natural matte finish.',
    price: 899,
    originalPrice: 1099,
    discount: 18,
    category: 'Beauty',
    brand: 'Lakme',
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500'],
    rating: 4.3,
    numReviews: 445,
    stock: 200,
    features: ['SPF 45', '24hr Wear', 'Serum Enriched', 'Matte Finish'],
    specifications: new Map([['Shade', 'Multiple'], ['Coverage', 'Medium to Full'], ['Finish', 'Matte'], ['Weight', '30ml']]),
    isFeatured: true,
    tags: ['makeup', 'foundation', 'skincare']
  },
  {
    name: 'Forest Essentials Luxury Facial Kit',
    description: 'Complete facial kit with natural ingredients. Includes cleanser, toner, serum, and moisturizer.',
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    category: 'Beauty',
    brand: 'Forest Essentials',
    images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500'],
    rating: 4.5,
    numReviews: 178,
    stock: 80,
    features: ['Natural Ingredients', 'Complete Kit', 'Ayurvedic Formula', 'Luxury Packaging'],
    specifications: new Map([['Type', 'Facial Kit'], ['Skin Type', 'All'], ['Products', '4'], ['Weight', '200g']]),
    isFeatured: true,
    tags: ['skincare', 'ayurvedic', 'luxury']
  },
  {
    name: 'Mamaearth Vitamin C Serum',
    description: 'Face serum with vitamin C and hyaluronic acid. Brightens skin, reduces dark spots.',
    price: 549,
    originalPrice: 699,
    discount: 21,
    category: 'Beauty',
    brand: 'Mamaearth',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500'],
    rating: 4.4,
    numReviews: 523,
    stock: 300,
    features: ['Vitamin C', 'Hyaluronic Acid', 'Natural Ingredients', 'Dermatologist Tested'],
    specifications: new Map([['Volume', '30ml'], ['Skin Type', 'All'], ['Use', 'Daily'], ['Gender', 'Unisex']]),
    isFeatured: false,
    tags: ['serum', 'skincare', 'vitamin-c']
  },
  {
    name: 'LOreal Paris Revitalift Night Cream',
    description: 'Anti-aging night cream with Pro-Retinol and Hyaluronic Acid. Reduces wrinkles overnight.',
    price: 799,
    originalPrice: 999,
    discount: 20,
    category: 'Beauty',
    brand: "L'Oreal Paris",
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=500'],
    rating: 4.4,
    numReviews: 345,
    stock: 250,
    features: ['Pro-Retinol', 'Hyaluronic Acid', 'Anti-Aging', 'Night Repair'],
    specifications: new Map([['Volume', '50ml'], ['Skin Type', 'All'], ['Use', 'Night'], ['Gender', 'Women']]),
    isFeatured: false,
    tags: ['night-cream', 'anti-aging', 'skincare']
  },
  {
    name: 'MyGlamm Perfect Curves Kajal',
    description: 'Intense black kajal with smudge-proof formula. Long-lasting 12hr wear.',
    price: 299,
    originalPrice: 399,
    discount: 25,
    category: 'Beauty',
    brand: 'MyGlamm',
    images: ['https://images.unsplash.com/photo-1631214524020-3c69bcd82b44?w=500'],
    rating: 4.3,
    numReviews: 678,
    stock: 400,
    features: ['Smudge-Proof', '12hr Wear', 'Intense Black', 'Safe Formula'],
    specifications: new Map([['Weight', '0.35g'], ['Type', 'Kajal'], ['Finish', 'Matte'], ['Duration', '12 hours']]),
    isFeatured: false,
    tags: ['kajal', 'eyes', 'makeup']
  },

  // ==================== HOME ====================
  {
    name: 'Godrej Interio Sofa Set',
    description: '3+1+1 sofa set with premium fabric upholstery. Solid wood frame, high-density foam.',
    price: 45999,
    originalPrice: 54999,
    discount: 16,
    category: 'Home',
    brand: 'Godrej',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500'],
    rating: 4.2,
    numReviews: 67,
    stock: 15,
    features: ['Premium Fabric', 'Solid Wood Frame', 'High-Density Foam', '5 Year Warranty'],
    specifications: new Map([['Seating', '3+1+1'], ['Material', 'Fabric/Wood'], ['Dimensions', 'L: 84 W: 36 H: 34'], ['Color', 'Multiple']]),
    isFeatured: true,
    tags: ['furniture', 'sofa', 'living-room']
  },
  {
    name: 'Urban Company Home Cleaning Kit',
    description: 'Complete home cleaning kit with microfiber cloths, brushes, and cleaning solutions.',
    price: 999,
    originalPrice: 1299,
    discount: 23,
    category: 'Home',
    brand: 'Urban Company',
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500'],
    rating: 4.2,
    numReviews: 345,
    stock: 180,
    features: ['Microfiber Cloths', 'Cleaning Brushes', 'Eco-Friendly', 'Multi-Surface'],
    specifications: new Map([['Items', '12'], ['Type', 'Cleaning Kit'], ['Material', 'Microfiber'], ['Warranty', '1 Year']]),
    isFeatured: false,
    tags: ['cleaning', 'home', 'kit']
  },
  {
    name: 'Solimo Bamboo Bedsheet Set',
    description: 'King size bedsheet with 2 pillow covers. 400 thread count, ultra-soft feel.',
    price: 1499,
    originalPrice: 1999,
    discount: 25,
    category: 'Home',
    brand: 'Solimo',
    images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500'],
    rating: 4.4,
    numReviews: 892,
    stock: 300,
    features: ['400 Thread Count', 'King Size', '2 Pillow Covers', 'Machine Washable'],
    specifications: new Map([['Size', 'King (274x274cm)'], ['Material', 'Cotton'], ['Thread Count', '400'], ['Includes', 'Bedsheet + 2 Pillow Covers']]),
    isFeatured: true,
    tags: ['bedsheet', 'bedroom', 'home-decor']
  },
  {
    name: 'Cello Opalware Dinner Set',
    description: '35 piece opalware dinner set. Microwave and dishwasher safe, elegant design.',
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    category: 'Home',
    brand: 'Cello',
    images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=500'],
    rating: 4.5,
    numReviews: 456,
    stock: 120,
    features: ['35 Pieces', 'Microwave Safe', 'Dishwasher Safe', 'Break Resistant'],
    specifications: new Map([['Pieces', '35'], ['Material', 'Opalware'], ['Safe', 'Microwave/Dishwasher'], ['Color', 'White with Design']]),
    isFeatured: false,
    tags: ['dinner-set', 'kitchen', 'dining']
  },

  // ==================== APPLIANCES ====================
  {
    name: 'Philips Air Fryer HD9650/90',
    description: 'Rapid Air technology for healthier frying. 1.8kg capacity, digital display, 7 presets.',
    price: 12995,
    originalPrice: 15995,
    discount: 19,
    category: 'Appliances',
    brand: 'Philips',
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=500'],
    rating: 4.4,
    numReviews: 289,
    stock: 60,
    features: ['Rapid Air Tech', '1.8kg Capacity', 'Digital Display', '7 Presets'],
    specifications: new Map([['Capacity', '1.8kg'], ['Power', '2225W'], ['Presets', '7'], ['Timer', '60min']]),
    isFeatured: true,
    tags: ['air-fryer', 'kitchen', 'healthy']
  },
  {
    name: 'LG 55 inch 4K OLED TV',
    description: '55 inch OLED display with Dolby Vision IQ. AI ThinQ, webOS, 4 HDMI ports.',
    price: 119990,
    originalPrice: 139990,
    discount: 14,
    category: 'Appliances',
    brand: 'LG',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500'],
    rating: 4.7,
    numReviews: 89,
    stock: 30,
    features: ['OLED Display', 'Dolby Vision IQ', 'AI ThinQ', 'G-Sync Compatible'],
    specifications: new Map([['Display', '55 inch OLED'], ['Resolution', '4K'], ['Refresh Rate', '120Hz'], ['HDR', 'Dolby Vision']]),
    isFeatured: false,
    tags: ['tv', 'oled', 'smart-tv']
  },
  {
    name: 'Whirlpool 7kg Front Load Washing Machine',
    description: '7kg capacity, 1200 RPM, 6th Sense technology, steam wash, Wi-Fi enabled.',
    price: 34990,
    originalPrice: 42990,
    discount: 19,
    category: 'Appliances',
    brand: 'Whirlpool',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500'],
    rating: 4.4,
    numReviews: 234,
    stock: 25,
    features: ['6th Sense Technology', 'Steam Wash', 'Wi-Fi Enabled', '1200 RPM'],
    specifications: new Map([['Capacity', '7kg'], ['RPM', '1200'], ['Energy Rating', '5 Star'], ['Warranty', '10 Years Motor']]),
    isFeatured: true,
    tags: ['washing-machine', 'front-load', 'appliance']
  },
  {
    name: 'Voltas 1.5 Ton 5 Star Inverter AC',
    description: '5 Star inverter split AC with adjustable cooling, anti-dust filter, and auto-restart.',
    price: 38990,
    originalPrice: 45990,
    discount: 15,
    category: 'Appliances',
    brand: 'Voltas',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500'],
    rating: 4.3,
    numReviews: 312,
    stock: 35,
    features: ['5 Star Rating', 'Inverter Technology', 'Anti-Dust Filter', 'Auto Restart'],
    specifications: new Map([['Capacity', '1.5 Ton'], ['Star Rating', '5 Star'], ['Type', 'Split Inverter'], ['Warranty', '1+4 Years']]),
    isFeatured: true,
    tags: ['ac', 'air-conditioner', 'inverter']
  },
  {
    name: 'Kent Grand Plus RO Water Purifier',
    description: 'RO+UV+UF+TDS control, 9L tank, 20L/hr purification, saves water with mineral RO.',
    price: 14999,
    originalPrice: 18999,
    discount: 21,
    category: 'Appliances',
    brand: 'Kent',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500'],
    rating: 4.4,
    numReviews: 567,
    stock: 50,
    features: ['RO+UV+UF', '9L Tank', '20L/hr', 'TDS Controller'],
    specifications: new Map([['Purification', 'RO+UV+UF'], ['Tank', '9 Liters'], ['Output', '20L/hr'], ['Warranty', '1 Year']]),
    isFeatured: false,
    tags: ['water-purifier', 'ro', 'kent']
  },

  // ==================== SPORTS ====================
  {
    name: 'Yonex Astrox 99 Pro Badminton Racket',
    description: 'Professional grade racket with Nanomesh Neo technology. Head heavy balance for power.',
    price: 18999,
    originalPrice: 21999,
    discount: 14,
    category: 'Sports',
    brand: 'Yonex',
    images: ['https://images.unsplash.com/photo-1617886903355-9354bb57771f?w=500'],
    rating: 4.7,
    numReviews: 123,
    stock: 40,
    features: ['Nanomesh Neo', 'Head Heavy', 'Isometric Head', 'Control Support Cap'],
    specifications: new Map([['Weight', '88g'], ['Balance', 'Head Heavy'], ['Flex', 'Stiff'], ['Tension', 'Up to 30lbs']]),
    isFeatured: true,
    tags: ['badminton', 'racket', 'professional']
  },
  {
    name: 'Adidas Ultraboost 22 Running Shoes',
    description: 'Energy-returning Boost midsole. Primeknit upper, Continental rubber outsole.',
    price: 15999,
    originalPrice: 17999,
    discount: 11,
    category: 'Sports',
    brand: 'Adidas',
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500'],
    rating: 4.6,
    numReviews: 234,
    stock: 85,
    features: ['Boost Midsole', 'Primeknit Upper', 'Continental Rubber', 'Energy Return'],
    specifications: new Map([['Type', 'Running'], ['Drop', '10mm'], ['Weight', '310g'], ['Surface', 'Road']]),
    isFeatured: false,
    tags: ['running', 'shoes', 'performance']
  },
  {
    name: 'Cosco Cricket Kit',
    description: 'Complete cricket kit for professionals. Includes bat, pads, gloves, helmet and bag.',
    price: 8999,
    originalPrice: 11999,
    discount: 25,
    category: 'Sports',
    brand: 'Cosco',
    images: ['https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=500'],
    rating: 4.3,
    numReviews: 178,
    stock: 45,
    features: ['Complete Kit', 'English Willow Bat', 'Helmet Included', 'Kit Bag'],
    specifications: new Map([['Bat', 'English Willow'], ['Size', 'Full'], ['Includes', '7 Items'], ['Age', '15+']]),
    isFeatured: true,
    tags: ['cricket', 'sports-kit', 'bat']
  },
  {
    name: 'Nivia Football Storm',
    description: 'FIFA quality pro football for training and matches. PU material, 32 panel design.',
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    category: 'Sports',
    brand: 'Nivia',
    images: ['https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=500'],
    rating: 4.4,
    numReviews: 456,
    stock: 150,
    features: ['FIFA Quality', 'PU Material', '32 Panel', 'Hand Stitched'],
    specifications: new Map([['Size', '5'], ['Material', 'PU'], ['Panels', '32'], ['Weight', '410-450g']]),
    isFeatured: false,
    tags: ['football', 'soccer', 'sports']
  },
  {
    name: 'Decathlon Gym Dumbbell Set',
    description: '20kg adjustable dumbbell set with rack. Chrome plated, anti-roll design.',
    price: 3999,
    originalPrice: 5499,
    discount: 27,
    category: 'Sports',
    brand: 'Decathlon',
    images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500'],
    rating: 4.5,
    numReviews: 678,
    stock: 80,
    features: ['20kg Total', 'Chrome Plated', 'Anti-Roll Design', 'With Rack'],
    specifications: new Map([['Weight', '20kg set'], ['Material', 'Chrome'], ['Plates', '10 pairs'], ['Bar Length', '35cm']]),
    isFeatured: true,
    tags: ['dumbbell', 'gym', 'fitness']
  },

  // ==================== GROCERY ====================
  {
    name: 'Tata Sampann Unpolished Toor Dal',
    description: 'Premium quality unpolished toor dal. 1kg pack, rich in protein, easy to digest.',
    price: 140,
    originalPrice: 160,
    discount: 13,
    category: 'Grocery',
    brand: 'Tata Sampann',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500'],
    rating: 4.5,
    numReviews: 567,
    stock: 500,
    features: ['Unpolished', 'High Protein', 'Easy to Digest', 'No Preservatives'],
    specifications: new Map([['Weight', '1kg'], ['Type', 'Toor Dal'], ['Packaging', 'Pouch'], ['Origin', 'India']]),
    isFeatured: true,
    tags: ['grocery', 'dal', 'staple']
  },
  {
    name: 'Amul Taaza Homogenised Milk',
    description: 'Fresh homogenised milk, 1 liter. Pasteurized, rich in calcium and protein.',
    price: 68,
    originalPrice: 72,
    discount: 6,
    category: 'Grocery',
    brand: 'Amul',
    images: ['https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500'],
    rating: 4.6,
    numReviews: 789,
    stock: 1000,
    features: ['Pasteurized', 'Homogenised', 'Rich in Calcium', 'Fresh'],
    specifications: new Map([['Volume', '1 Liter'], ['Fat', '3%'], ['Type', 'Cow Milk'], ['Shelf Life', '2 days']]),
    isFeatured: false,
    tags: ['milk', 'dairy', 'fresh']
  },
  {
    name: 'Aashirvaad Atta 10kg',
    description: 'Superior MP whole wheat atta. Ideal for soft rotis, rich in fiber.',
    price: 389,
    originalPrice: 450,
    discount: 14,
    category: 'Grocery',
    brand: 'Aashirvaad',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500'],
    rating: 4.6,
    numReviews: 2345,
    stock: 800,
    features: ['Whole Wheat', 'High Fiber', 'Soft Rotis', 'No Maida'],
    specifications: new Map([['Weight', '10kg'], ['Type', 'Whole Wheat'], ['Origin', 'Madhya Pradesh'], ['Packaging', 'Bag']]),
    isFeatured: true,
    tags: ['atta', 'wheat', 'staple']
  },
  {
    name: 'Fortune Sunflower Oil 5L',
    description: 'Light and healthy sunflower oil. Rich in Vitamin E, low in saturated fat.',
    price: 699,
    originalPrice: 799,
    discount: 13,
    category: 'Grocery',
    brand: 'Fortune',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500'],
    rating: 4.4,
    numReviews: 1234,
    stock: 600,
    features: ['Rich in Vitamin E', 'Low Saturated Fat', '5 Liter', 'Light & Healthy'],
    specifications: new Map([['Volume', '5 Liters'], ['Type', 'Sunflower Oil'], ['Packaging', 'Jar'], ['Origin', 'India']]),
    isFeatured: false,
    tags: ['oil', 'cooking', 'grocery']
  },
  {
    name: 'Nescafe Classic Instant Coffee 200g',
    description: 'Rich and aromatic instant coffee. Made from 100% pure coffee beans.',
    price: 499,
    originalPrice: 599,
    discount: 17,
    category: 'Grocery',
    brand: 'Nescafe',
    images: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500'],
    rating: 4.5,
    numReviews: 3456,
    stock: 700,
    features: ['100% Pure Coffee', 'Rich Aroma', 'Instant', '200g Pack'],
    specifications: new Map([['Weight', '200g'], ['Type', 'Instant Coffee'], ['Caffeine', 'Regular'], ['Packaging', 'Jar']]),
    isFeatured: true,
    tags: ['coffee', 'instant', 'beverage']
  },

  // ==================== BOOKS ====================
  {
    name: 'Atomic Habits by James Clear',
    description: 'Bestselling self-help book about building good habits and breaking bad ones.',
    price: 499,
    originalPrice: 699,
    discount: 29,
    category: 'Books',
    brand: 'Penguin',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500'],
    rating: 4.8,
    numReviews: 1250,
    stock: 200,
    features: ['Bestseller', 'Self-Help', 'Paperback', '320 Pages'],
    specifications: new Map([['Author', 'James Clear'], ['Pages', '320'], ['Language', 'English'], ['Format', 'Paperback']]),
    isFeatured: true,
    tags: ['book', 'self-help', 'bestseller']
  },
  {
    name: 'Ikigai: The Japanese Secret',
    description: 'Discover the Japanese concept of ikigai and find your purpose in life.',
    price: 399,
    originalPrice: 599,
    discount: 33,
    category: 'Books',
    brand: 'Penguin',
    images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500'],
    rating: 4.6,
    numReviews: 890,
    stock: 150,
    features: ['Philosophy', 'Self-Improvement', 'Paperback', '208 Pages'],
    specifications: new Map([['Author', 'Héctor García'], ['Pages', '208'], ['Language', 'English'], ['Format', 'Paperback']]),
    isFeatured: true,
    tags: ['book', 'philosophy', 'motivation']
  },
  {
    name: 'The Psychology of Money',
    description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel.',
    price: 449,
    originalPrice: 599,
    discount: 25,
    category: 'Books',
    brand: 'HarperCollins',
    images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500'],
    rating: 4.7,
    numReviews: 756,
    stock: 180,
    features: ['Finance', 'Psychology', 'Paperback', '256 Pages'],
    specifications: new Map([['Author', 'Morgan Housel'], ['Pages', '256'], ['Language', 'English'], ['Format', 'Paperback']]),
    isFeatured: false,
    tags: ['book', 'finance', 'psychology']
  },
  {
    name: 'Rich Dad Poor Dad',
    description: 'Robert Kiyosaki shares lessons about money and financial independence.',
    price: 349,
    originalPrice: 499,
    discount: 30,
    category: 'Books',
    brand: 'Manjul Publishing',
    images: ['https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=500'],
    rating: 4.7,
    numReviews: 2345,
    stock: 300,
    features: ['Personal Finance', 'Bestseller', 'Paperback', '240 Pages'],
    specifications: new Map([['Author', 'Robert Kiyosaki'], ['Pages', '240'], ['Language', 'English'], ['Format', 'Paperback']]),
    isFeatured: true,
    tags: ['book', 'finance', 'bestseller']
  },
  {
    name: 'Wings of Fire by APJ Abdul Kalam',
    description: 'Autobiography of India\'s missile man and former President Dr. APJ Abdul Kalam.',
    price: 249,
    originalPrice: 350,
    discount: 29,
    category: 'Books',
    brand: 'Universities Press',
    images: ['https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=500'],
    rating: 4.9,
    numReviews: 3456,
    stock: 400,
    features: ['Autobiography', 'Inspirational', 'Paperback', '196 Pages'],
    specifications: new Map([['Author', 'APJ Abdul Kalam'], ['Pages', '196'], ['Language', 'English'], ['Format', 'Paperback']]),
    isFeatured: true,
    tags: ['book', 'biography', 'inspirational', 'india']
  },

  // ==================== TOYS ====================
  {
    name: 'LEGO Technic Bugatti Chiron',
    description: 'Build your own Bugatti Chiron with 3599 pieces. For ages 16+.',
    price: 32999,
    originalPrice: 37999,
    discount: 13,
    category: 'Toys',
    brand: 'LEGO',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500'],
    rating: 4.9,
    numReviews: 234,
    stock: 45,
    features: ['3599 Pieces', 'Technic Series', 'Ages 16+', 'Premium Set'],
    specifications: new Map([['Pieces', '3599'], ['Age', '16+'], ['Dimensions', '56 x 25 x 14 cm'], ['Weight', '3.2kg']]),
    isFeatured: true,
    tags: ['lego', 'toys', 'building']
  },
  {
    name: 'Hot Wheels Ultimate Garage',
    description: 'Multi-level garage with 100+ cars storage. Includes 5 Hot Wheels cars.',
    price: 5999,
    originalPrice: 7999,
    discount: 25,
    category: 'Toys',
    brand: 'Hot Wheels',
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500'],
    rating: 4.5,
    numReviews: 567,
    stock: 80,
    features: ['100+ Cars Storage', 'Multi-Level', '5 Cars Included', 'Ages 5+'],
    specifications: new Map([['Height', '83cm'], ['Age', '5+'], ['Cars Included', '5'], ['Material', 'Plastic']]),
    isFeatured: true,
    tags: ['hot-wheels', 'toys', 'garage']
  },
  {
    name: 'Barbie Dreamhouse',
    description: '3-story dreamhouse with elevator, pool, and 70+ accessories.',
    price: 14999,
    originalPrice: 17999,
    discount: 17,
    category: 'Toys',
    brand: 'Barbie',
    images: ['https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=500'],
    rating: 4.6,
    numReviews: 445,
    stock: 60,
    features: ['3 Stories', 'Working Elevator', 'Pool', '70+ Accessories'],
    specifications: new Map([['Height', '109cm'], ['Age', '3+'], ['Accessories', '70+'], ['Material', 'Plastic']]),
    isFeatured: false,
    tags: ['barbie', 'toys', 'dollhouse']
  },
  {
    name: 'Funskool Monopoly Classic',
    description: 'Classic board game of property trading. Includes 8 tokens, 28 title deed cards.',
    price: 799,
    originalPrice: 999,
    discount: 20,
    category: 'Toys',
    brand: 'Funskool',
    images: ['https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=500'],
    rating: 4.5,
    numReviews: 1234,
    stock: 200,
    features: ['Classic Edition', '8 Tokens', 'Family Game', 'Ages 8+'],
    specifications: new Map([['Age', '8+'], ['Players', '2-8'], ['Duration', '60-180 mins'], ['Language', 'English']]),
    isFeatured: false,
    tags: ['board-game', 'monopoly', 'family']
  },

  // ==================== FURNITURE ====================
  {
    name: 'Featherlite Executive Chair',
    description: 'Ergonomic office chair with lumbar support, mesh back, and adjustable height.',
    price: 8999,
    originalPrice: 11999,
    discount: 25,
    category: 'Furniture',
    brand: 'Featherlite',
    images: ['https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=500'],
    rating: 4.5,
    numReviews: 234,
    stock: 50,
    features: ['Ergonomic Design', 'Lumbar Support', 'Mesh Back', 'Adjustable Height'],
    specifications: new Map([['Material', 'Mesh/Metal'], ['Weight Capacity', '120kg'], ['Height', '120-135cm'], ['Warranty', '3 Years']]),
    isFeatured: true,
    tags: ['furniture', 'chair', 'office']
  },
  {
    name: 'Urban Ladder Study Table',
    description: 'Modern study table with drawers. Solid sheesham wood, walnut finish.',
    price: 15999,
    originalPrice: 19999,
    discount: 20,
    category: 'Furniture',
    brand: 'Urban Ladder',
    images: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500'],
    rating: 4.6,
    numReviews: 178,
    stock: 35,
    features: ['Solid Wood', '3 Drawers', 'Walnut Finish', 'Easy Assembly'],
    specifications: new Map([['Material', 'Sheesham Wood'], ['Dimensions', '120 x 60 x 75 cm'], ['Drawers', '3'], ['Finish', 'Walnut']]),
    isFeatured: true,
    tags: ['furniture', 'table', 'study']
  },
  {
    name: 'Nilkamal Plastic Wardrobe',
    description: '3-door plastic wardrobe with shelves and hanging space. Easy to assemble.',
    price: 7999,
    originalPrice: 9999,
    discount: 20,
    category: 'Furniture',
    brand: 'Nilkamal',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500'],
    rating: 4.3,
    numReviews: 345,
    stock: 60,
    features: ['3 Doors', 'Shelves Included', 'Hanging Space', 'Easy Assembly'],
    specifications: new Map([['Material', 'Plastic'], ['Dimensions', '91 x 46 x 183 cm'], ['Doors', '3'], ['Color', 'Brown']]),
    isFeatured: false,
    tags: ['furniture', 'wardrobe', 'storage']
  },
  {
    name: 'Pepperfry King Size Bed',
    description: 'King size bed with hydraulic storage. Solid engineered wood, walnut finish.',
    price: 28999,
    originalPrice: 35999,
    discount: 19,
    category: 'Furniture',
    brand: 'Pepperfry',
    images: ['https://images.unsplash.com/photo-1505693314120-0d443867891c?w=500'],
    rating: 4.4,
    numReviews: 189,
    stock: 20,
    features: ['Hydraulic Storage', 'King Size', 'Engineered Wood', '5 Year Warranty'],
    specifications: new Map([['Size', 'King (180x200cm)'], ['Material', 'Engineered Wood'], ['Storage', 'Hydraulic'], ['Finish', 'Walnut']]),
    isFeatured: true,
    tags: ['bed', 'bedroom', 'furniture', 'storage']
  },

  // ==================== KITCHEN ====================
  {
    name: 'Prestige Induction Cooktop',
    description: '2000W induction cooktop with preset menus. Touch control panel.',
    price: 2999,
    originalPrice: 3999,
    discount: 25,
    category: 'Kitchen',
    brand: 'Prestige',
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500'],
    rating: 4.5,
    numReviews: 678,
    stock: 120,
    features: ['2000W Power', 'Touch Control', 'Preset Menus', 'Auto Off'],
    specifications: new Map([['Power', '2000W'], ['Voltage', '220-240V'], ['Controls', 'Touch'], ['Warranty', '2 Years']]),
    isFeatured: true,
    tags: ['kitchen', 'induction', 'cooktop']
  },
  {
    name: 'Milton Water Bottle Set',
    description: 'Set of 3 stainless steel water bottles. 1000ml each, leak-proof.',
    price: 899,
    originalPrice: 1199,
    discount: 25,
    category: 'Kitchen',
    brand: 'Milton',
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500'],
    rating: 4.6,
    numReviews: 567,
    stock: 250,
    features: ['Stainless Steel', 'Leak-Proof', '1000ml Each', 'Set of 3'],
    specifications: new Map([['Material', 'Steel'], ['Capacity', '1000ml'], ['Quantity', '3'], ['Color', 'Assorted']]),
    isFeatured: true,
    tags: ['kitchen', 'bottle', 'steel']
  },
  {
    name: 'Wonderchef Stand Mixer',
    description: '1000W stand mixer with 5-speed settings. Includes dough hook and beater.',
    price: 6999,
    originalPrice: 8999,
    discount: 22,
    category: 'Kitchen',
    brand: 'Wonderchef',
    images: ['https://images.unsplash.com/photo-1586231515214-48dbd2e8a943?w=500'],
    rating: 4.4,
    numReviews: 234,
    stock: 45,
    features: ['1000W Motor', '5 Speeds', 'Dough Hook', 'Beater Included'],
    specifications: new Map([['Power', '1000W'], ['Speeds', '5'], ['Bowl Capacity', '4.5L'], ['Warranty', '2 Years']]),
    isFeatured: false,
    tags: ['kitchen', 'mixer', 'stand']
  },
  {
    name: 'Hawkins Pressure Cooker 5L',
    description: 'Classic Hawkins hard anodised pressure cooker. 5 litre, fast cooking.',
    price: 2199,
    originalPrice: 2799,
    discount: 21,
    category: 'Kitchen',
    brand: 'Hawkins',
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=500'],
    rating: 4.7,
    numReviews: 1234,
    stock: 180,
    features: ['Hard Anodised', '5 Litre', 'Fast Cooking', 'ISI Certified'],
    specifications: new Map([['Capacity', '5 Liters'], ['Material', 'Hard Anodised'], ['Compatible', 'All Stoves'], ['Warranty', '5 Years']]),
    isFeatured: false,
    tags: ['pressure-cooker', 'kitchen', 'cooking']
  },

  // ==================== AUTOMOTIVE ====================
  {
    name: '3M Car Care Kit',
    description: 'Complete car care kit with wax, polish, shampoo, and microfiber cloths.',
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    category: 'Automotive',
    brand: '3M',
    images: ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=500'],
    rating: 4.4,
    numReviews: 678,
    stock: 120,
    features: ['Complete Kit', 'Wax & Polish', 'Shampoo', 'Microfiber Cloths'],
    specifications: new Map([['Items', '8'], ['Type', 'Car Care'], ['Brand', '3M'], ['Warranty', '1 Year']]),
    isFeatured: true,
    tags: ['automotive', 'car-care', 'cleaning']
  },
  {
    name: 'GoMechanic Car Vacuum Cleaner',
    description: 'Portable car vacuum cleaner with HEPA filter. 12V power.',
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    category: 'Automotive',
    brand: 'GoMechanic',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500'],
    rating: 4.3,
    numReviews: 432,
    stock: 200,
    features: ['Portable', 'HEPA Filter', '12V Power', 'Wet & Dry'],
    specifications: new Map([['Power', '120W'], ['Voltage', '12V'], ['Cable Length', '5m'], ['Weight', '1.2kg']]),
    isFeatured: true,
    tags: ['automotive', 'vacuum', 'cleaning']
  },
  {
    name: 'Tyre Inflator Digital Air Compressor',
    description: 'Digital tyre inflator with pressure gauge. LED light, auto shut-off.',
    price: 1899,
    originalPrice: 2499,
    discount: 24,
    category: 'Automotive',
    brand: 'Michelin',
    images: ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=500'],
    rating: 4.5,
    numReviews: 389,
    stock: 150,
    features: ['Digital Display', 'Auto Shut-off', 'LED Light', 'Multiple Nozzles'],
    specifications: new Map([['Power', '150W'], ['Pressure', '0-150 PSI'], ['Cord Length', '3m'], ['Weight', '1.5kg']]),
    isFeatured: false,
    tags: ['automotive', 'inflator', 'tyre']
  },
  {
    name: 'Varta Car Battery 55Ah',
    description: 'Maintenance-free car battery. 55Ah capacity, 520A cold cranking amps.',
    price: 5499,
    originalPrice: 6999,
    discount: 21,
    category: 'Automotive',
    brand: 'Varta',
    images: ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=500'],
    rating: 4.4,
    numReviews: 234,
    stock: 60,
    features: ['Maintenance Free', '55Ah', '520A CCA', '36 Month Warranty'],
    specifications: new Map([['Capacity', '55Ah'], ['CCA', '520A'], ['Voltage', '12V'], ['Warranty', '36 Months']]),
    isFeatured: false,
    tags: ['automotive', 'battery', 'car']
  },

  // ==================== BABY PRODUCTS ====================
  {
    name: 'Himalaya Baby Care Gift Set',
    description: 'Complete baby care set with shampoo, lotion, oil, powder, and cream.',
    price: 899,
    originalPrice: 1199,
    discount: 25,
    category: 'Baby Products',
    brand: 'Himalaya',
    images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500'],
    rating: 4.7,
    numReviews: 567,
    stock: 180,
    features: ['Complete Set', 'Herbal', 'Dermatologist Tested', 'Paraben Free'],
    specifications: new Map([['Items', '5'], ['Age', '0+'], ['Weight', '500g'], ['Type', 'Gift Set']]),
    isFeatured: true,
    tags: ['baby', 'care', 'herbal']
  },
  {
    name: 'Pampers Premium Care Diapers',
    description: 'Premium diapers with wetness indicator. Pack of 54, size M.',
    price: 799,
    originalPrice: 999,
    discount: 20,
    category: 'Baby Products',
    brand: 'Pampers',
    images: ['https://images.unsplash.com/photo-1519689680058-324335c77eba?w=500'],
    rating: 4.6,
    numReviews: 890,
    stock: 300,
    features: ['Wetness Indicator', 'Soft & Comfortable', 'Up to 12 Hours', 'Size M'],
    specifications: new Map([['Size', 'M'], ['Count', '54'], ['Weight', '5-11kg'], ['Type', 'Premium']]),
    isFeatured: false,
    tags: ['baby', 'diapers', 'premium']
  },
  {
    name: 'Fisher-Price Rock n Play Sleeper',
    description: 'Portable baby sleeper with rocking motion and soothing vibrations.',
    price: 4999,
    originalPrice: 6499,
    discount: 23,
    category: 'Baby Products',
    brand: 'Fisher-Price',
    images: ['https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=500'],
    rating: 4.4,
    numReviews: 345,
    stock: 70,
    features: ['Rocking Motion', 'Soothing Vibrations', 'Portable', 'Machine Washable'],
    specifications: new Map([['Weight Limit', '11kg'], ['Age', '0-6 months'], ['Dimensions', '56 x 36 x 28 cm'], ['Material', 'Fabric']]),
    isFeatured: true,
    tags: ['baby', 'sleeper', 'rocking']
  },
  {
    name: 'Mee Mee Baby Stroller',
    description: 'Lightweight baby stroller with reversible seat and adjustable canopy.',
    price: 6999,
    originalPrice: 8999,
    discount: 22,
    category: 'Baby Products',
    brand: 'Mee Mee',
    images: ['https://images.unsplash.com/photo-1591088398332-8a7791972843?w=500'],
    rating: 4.3,
    numReviews: 234,
    stock: 55,
    features: ['Reversible Seat', 'Adjustable Canopy', 'Lightweight', 'Safety Harness'],
    specifications: new Map([['Weight', '6.5kg'], ['Age', '0-3 years'], ['Max Load', '15kg'], ['Folded Size', '80 x 45 x 30cm']]),
    isFeatured: false,
    tags: ['baby', 'stroller', 'pram']
  },

  // ==================== JEWELLERY ====================
  {
    name: 'Tanishq Gold Mangalsutra',
    description: '22KT gold mangalsutra with diamond pendant. Traditional design with modern touch.',
    price: 28999,
    originalPrice: 32999,
    discount: 12,
    category: 'Jewellery',
    brand: 'Tanishq',
    images: ['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500'],
    rating: 4.8,
    numReviews: 234,
    stock: 25,
    features: ['22KT Gold', 'Diamond Pendant', 'BIS Hallmarked', 'Traditional Design'],
    specifications: new Map([['Gold', '22KT'], ['Weight', '5g'], ['Length', '18 inches'], ['Certification', 'BIS Hallmark']]),
    isFeatured: true,
    tags: ['jewellery', 'gold', 'mangalsutra', 'wedding']
  },
  {
    name: 'Malabar Gold Silver Anklets',
    description: 'Pure 92.5 sterling silver anklets with traditional Indian design. Set of 2.',
    price: 2499,
    originalPrice: 2999,
    discount: 17,
    category: 'Jewellery',
    brand: 'Malabar Gold',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=500'],
    rating: 4.5,
    numReviews: 345,
    stock: 80,
    features: ['92.5 Sterling Silver', 'Set of 2', 'Traditional Design', 'BIS Hallmarked'],
    specifications: new Map([['Metal', '92.5 Silver'], ['Weight', '20g pair'], ['Size', 'Adjustable'], ['Certification', 'BIS Hallmark']]),
    isFeatured: true,
    tags: ['jewellery', 'silver', 'anklet', 'traditional']
  },
  {
    name: 'CaratLane Diamond Stud Earrings',
    description: '18KT white gold diamond stud earrings. 0.20 carat total diamond weight.',
    price: 12999,
    originalPrice: 15999,
    discount: 19,
    category: 'Jewellery',
    brand: 'CaratLane',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
    rating: 4.7,
    numReviews: 156,
    stock: 40,
    features: ['18KT White Gold', '0.20 Carat Diamond', 'IGI Certified', 'Push Back Closure'],
    specifications: new Map([['Gold', '18KT White Gold'], ['Diamond', '0.20 Carat'], ['Certification', 'IGI'], ['Closure', 'Push Back']]),
    isFeatured: false,
    tags: ['jewellery', 'diamond', 'earrings', 'gold']
  },
  {
    name: 'Voylla Oxidised Silver Jhumkas',
    description: 'Traditional oxidised silver jhumka earrings with meenakari work.',
    price: 599,
    originalPrice: 899,
    discount: 33,
    category: 'Jewellery',
    brand: 'Voylla',
    images: ['https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=500'],
    rating: 4.3,
    numReviews: 678,
    stock: 200,
    features: ['Oxidised Silver', 'Meenakari Work', 'Ethnic Design', 'Nickel Free'],
    specifications: new Map([['Material', 'Oxidised Silver'], ['Type', 'Jhumka'], ['Occasion', 'Ethnic/Casual'], ['Weight', '15g pair']]),
    isFeatured: true,
    tags: ['jewellery', 'jhumka', 'ethnic', 'silver']
  },

  // ==================== HEALTH & WELLNESS ====================
  {
    name: 'Himalaya Liv.52 DS Tablets',
    description: 'Double strength liver care tablets. Improves liver function and appetite.',
    price: 399,
    originalPrice: 499,
    discount: 20,
    category: 'Health',
    brand: 'Himalaya',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500'],
    rating: 4.6,
    numReviews: 2345,
    stock: 500,
    features: ['Double Strength', 'Liver Care', 'Ayurvedic', '60 Tablets'],
    specifications: new Map([['Tablets', '60'], ['Type', 'Ayurvedic'], ['Form', 'Tablet'], ['Dosage', '1-2 tablets twice daily']]),
    isFeatured: true,
    tags: ['health', 'liver', 'ayurvedic', 'tablets']
  },
  {
    name: 'Oziva Protein & Herbs for Women',
    description: 'Plant-based protein powder with herbs for women. 23g protein per serving.',
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    category: 'Health',
    brand: 'Oziva',
    images: ['https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500'],
    rating: 4.4,
    numReviews: 567,
    stock: 200,
    features: ['23g Protein', 'Plant Based', 'Herbs Added', 'No Artificial Sweeteners'],
    specifications: new Map([['Protein', '23g per serving'], ['Servings', '30'], ['Flavor', 'Chocolate'], ['Weight', '1kg']]),
    isFeatured: true,
    tags: ['protein', 'health', 'women', 'plant-based']
  },
  {
    name: 'Omron HEM-7120 Blood Pressure Monitor',
    description: 'Automatic upper arm blood pressure monitor. Clinically validated, easy to use.',
    price: 1799,
    originalPrice: 2299,
    discount: 22,
    category: 'Health',
    brand: 'Omron',
    images: ['https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=500'],
    rating: 4.5,
    numReviews: 1234,
    stock: 150,
    features: ['Clinically Validated', 'Memory for 30 Readings', 'Easy Wrap Cuff', 'Irregular Heartbeat Detection'],
    specifications: new Map([['Type', 'Upper Arm'], ['Memory', '30 readings'], ['Cuff Size', '22-32cm'], ['Power', 'Batteries/Adapter']]),
    isFeatured: false,
    tags: ['health', 'blood-pressure', 'monitor', 'medical']
  },
  {
    name: 'Wellbeing Nutrition Multivitamin',
    description: 'Daily multivitamin with 30+ vitamins and minerals. Immunity booster.',
    price: 899,
    originalPrice: 1199,
    discount: 25,
    category: 'Health',
    brand: 'Wellbeing Nutrition',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500'],
    rating: 4.3,
    numReviews: 456,
    stock: 300,
    features: ['30+ Vitamins', 'Immunity Boost', 'Vegetarian', '60 Tablets'],
    specifications: new Map([['Tablets', '60'], ['Vitamins', '30+'], ['Type', 'Vegetarian'], ['Dosage', '1 tablet daily']]),
    isFeatured: false,
    tags: ['health', 'multivitamin', 'immunity', 'supplements']
  },

  // ==================== STATIONERY & OFFICE ====================
  {
    name: 'Parker Jotter Ballpoint Pen',
    description: 'Classic Parker Jotter pen with stainless steel body. Smooth writing experience.',
    price: 599,
    originalPrice: 799,
    discount: 25,
    category: 'Stationery',
    brand: 'Parker',
    images: ['https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=500'],
    rating: 4.6,
    numReviews: 890,
    stock: 300,
    features: ['Stainless Steel Body', 'Smooth Writing', 'Refillable', 'Classic Design'],
    specifications: new Map([['Material', 'Stainless Steel'], ['Ink', 'Blue'], ['Tip', 'Medium'], ['Refillable', 'Yes']]),
    isFeatured: true,
    tags: ['pen', 'stationery', 'parker', 'office']
  },
  {
    name: 'Classmate Notebook Set of 6',
    description: 'Single line notebooks for school and college. 200 pages each, ruled.',
    price: 299,
    originalPrice: 399,
    discount: 25,
    category: 'Stationery',
    brand: 'Classmate',
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=500'],
    rating: 4.4,
    numReviews: 3456,
    stock: 800,
    features: ['200 Pages Each', 'Single Line', 'Set of 6', 'FSC Certified Paper'],
    specifications: new Map([['Pages', '200 each'], ['Size', 'A4'], ['Ruling', 'Single Line'], ['Pack', '6 notebooks']]),
    isFeatured: false,
    tags: ['notebook', 'stationery', 'school', 'college']
  },
  {
    name: 'Casio Scientific Calculator FX-991EX',
    description: '552 functions scientific calculator with spreadsheet, vector, and equation modes.',
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    category: 'Stationery',
    brand: 'Casio',
    images: ['https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=500'],
    rating: 4.8,
    numReviews: 2345,
    stock: 400,
    features: ['552 Functions', 'Spreadsheet Mode', 'Solar + Battery', 'High Resolution Display'],
    specifications: new Map([['Functions', '552'], ['Display', 'High Res'], ['Power', 'Solar+Battery'], ['Memory', '32 variables']]),
    isFeatured: true,
    tags: ['calculator', 'scientific', 'casio', 'stationery']
  },

  // ==================== PET SUPPLIES ====================
  {
    name: 'Pedigree Adult Dog Food 10kg',
    description: 'Complete nutrition for adult dogs. Chicken and vegetables flavour.',
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    category: 'Pet Supplies',
    brand: 'Pedigree',
    images: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500'],
    rating: 4.5,
    numReviews: 1234,
    stock: 200,
    features: ['Complete Nutrition', 'Chicken & Veg', '10kg Pack', 'No Artificial Colors'],
    specifications: new Map([['Weight', '10kg'], ['Flavor', 'Chicken & Vegetables'], ['Age', 'Adult 1+ year'], ['Breed', 'All Breeds']]),
    isFeatured: true,
    tags: ['dog-food', 'pet', 'pedigree']
  },
  {
    name: 'Whiskas Cat Food Tuna 1.2kg',
    description: 'Ocean fish cat food with tuna flavour. Complete and balanced nutrition.',
    price: 699,
    originalPrice: 899,
    discount: 22,
    category: 'Pet Supplies',
    brand: 'Whiskas',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500'],
    rating: 4.4,
    numReviews: 678,
    stock: 300,
    features: ['Ocean Fish', 'Complete Nutrition', '1.2kg Pack', 'Omega 3 & 6'],
    specifications: new Map([['Weight', '1.2kg'], ['Flavor', 'Tuna'], ['Age', 'Adult'], ['Type', 'Dry Food']]),
    isFeatured: false,
    tags: ['cat-food', 'pet', 'whiskas']
  },
  {
    name: 'Trixie Dog Leash and Collar Set',
    description: 'Adjustable nylon leash and collar set for dogs. Reflective strip for night walks.',
    price: 599,
    originalPrice: 799,
    discount: 25,
    category: 'Pet Supplies',
    brand: 'Trixie',
    images: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500'],
    rating: 4.3,
    numReviews: 456,
    stock: 180,
    features: ['Reflective Strip', 'Adjustable', 'Nylon Material', 'Set of Leash + Collar'],
    specifications: new Map([['Material', 'Nylon'], ['Leash Length', '1.5m'], ['Collar Size', 'Adjustable'], ['Color', 'Multiple']]),
    isFeatured: false,
    tags: ['dog', 'leash', 'collar', 'pet']
  },

  // ==================== PERSONAL CARE ====================
  {
    name: 'Philips Wet & Dry Electric Shaver',
    description: 'Series 5000 electric shaver with aquatec technology for wet and dry shaving.',
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    category: 'Personal Care',
    brand: 'Philips',
    images: ['https://images.unsplash.com/photo-1621607512214-68297480165e?w=500'],
    rating: 4.4,
    numReviews: 567,
    stock: 80,
    features: ['Wet & Dry', 'AquaTec', '60min Battery', 'Pop-up Trimmer'],
    specifications: new Map([['Battery', '60 minutes'], ['Charging', '1 hour'], ['Head', '3 Blades'], ['Warranty', '2 Years']]),
    isFeatured: true,
    tags: ['shaver', 'grooming', 'men', 'electric']
  },
  {
    name: 'Dove Body Lotion 400ml',
    description: 'Intensive moisturizing body lotion with 1/4 moisturizing cream. For dry skin.',
    price: 299,
    originalPrice: 399,
    discount: 25,
    category: 'Personal Care',
    brand: 'Dove',
    images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500'],
    rating: 4.5,
    numReviews: 2345,
    stock: 500,
    features: ['1/4 Moisturizing Cream', '400ml', 'For Dry Skin', 'Dermatologist Recommended'],
    specifications: new Map([['Volume', '400ml'], ['Skin Type', 'Dry'], ['Fragrance', 'Mild'], ['Gender', 'Unisex']]),
    isFeatured: false,
    tags: ['lotion', 'moisturizer', 'body-care', 'dove']
  },
  {
    name: 'Colgate Total Toothpaste 150g',
    description: 'Total antibacterial toothpaste for complete oral care. 12-hour germ protection.',
    price: 149,
    originalPrice: 199,
    discount: 25,
    category: 'Personal Care',
    brand: 'Colgate',
    images: ['https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=500'],
    rating: 4.5,
    numReviews: 4567,
    stock: 1000,
    features: ['12hr Germ Protection', 'Antibacterial', 'Whitening', '150g'],
    specifications: new Map([['Weight', '150g'], ['Type', 'Total'], ['Flavor', 'Mint'], ['Protection', '12 Hours']]),
    isFeatured: false,
    tags: ['toothpaste', 'oral-care', 'colgate']
  },

  // ==================== GARDEN & OUTDOOR ====================
  {
    name: 'Ugaoo Plant Starter Kit',
    description: 'Complete plant growing kit with seeds, pots, soil, and tools. Grow your own garden.',
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    category: 'Garden',
    brand: 'Ugaoo',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=500'],
    rating: 4.5,
    numReviews: 567,
    stock: 150,
    features: ['10 Seed Varieties', '5 Pots Included', 'Organic Soil', 'Gardening Tools'],
    specifications: new Map([['Seeds', '10 varieties'], ['Pots', '5'], ['Soil', 'Organic'], ['Tools', 'Included']]),
    isFeatured: true,
    tags: ['garden', 'plants', 'seeds', 'kit']
  },
  {
    name: 'Bosch Cordless Drill Driver',
    description: '18V cordless drill with 2 speed settings, LED light, and carrying case.',
    price: 6999,
    originalPrice: 8999,
    discount: 22,
    category: 'Garden',
    brand: 'Bosch',
    images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500'],
    rating: 4.6,
    numReviews: 345,
    stock: 60,
    features: ['18V Battery', '2 Speed Settings', 'LED Light', 'Carrying Case'],
    specifications: new Map([['Voltage', '18V'], ['Chuck', '13mm'], ['Speeds', '2'], ['Torque', '55Nm']]),
    isFeatured: false,
    tags: ['drill', 'tools', 'bosch', 'cordless']
  }
];

mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/indian-shopping')
  .then(() => {
    console.log('MongoDB Connected');
    return Product.deleteMany({});
  })
  .then(() => {
    console.log('Old products deleted');
    return Product.insertMany(sampleProducts);
  })
  .then(() => {
    console.log(`✅ ${sampleProducts.length} products seeded successfully!`);
    process.exit();
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
